apiVersion: v1
kind: Service
metadata:
  name: users-frontend
  labels:
    app: udagram-frontend
spec:
  ports:
  - port: 80
    targetPort: 8100
    protocol: TCP
  selector:
    app: udagram-frontend